name: DynLight
main: anon.def9a2a4.dynlight.DynLightPlugin
version: ${version}
api-version: 1.21
author: def9a2a4
description: dynamic entity-based lights minecraft plugin

commands:
  dynlight:
    description: DynLight commands
    usage: /dynlight <help|enable|disable|info|reload|regen|stats>

permissions:
  dynlight.use:
    description: Toggle dynamic lights for yourself
    default: true
  dynlight.admin:
    description: Access to DynLight admin commands
    default: op
